#!/usr/bin/env python3
"""Convert 12x21 text sprites into VIC-II multicolour data and bitmap outlines."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
blocks, current = [], []
for line in (ROOT / "data/characters.txt").read_text().splitlines():
    line = line.strip()
    if not line or line.startswith("#"):
        if current:
            blocks.append(current)
            current = []
        continue
    current.append(line)
if current:
    blocks.append(current)
if len(blocks) != 4 or any(len(b) != 21 for b in blocks):
    raise SystemExit("Expected four character designs, each exactly 21 rows")
for b in blocks:
    if any(len(row) > 12 or set(row) - set(".123") for row in b):
        raise SystemExit("Rows must be at most 12 pixels wide using .123")

def asm_bytes(values):
    return "    !byte " + ",".join(f"${x:02x}" for x in values)

out = ["; Generated by tools/convert_sprites.py; do not edit.", "SpriteData:"]
for n, block in enumerate(blocks):
    out.append(f"Sprite{n}:")
    for row in block:
        row = row.ljust(12, ".")
        bits = []
        for i in range(0, 12, 4):
            value = 0
            for char in row[i:i+4]:
                value = (value << 2) | (0 if char == "." else int(char))
            bits.append(value)
        out.append(asm_bytes(bits))
    out.append("    !byte 0")
    out.append("")

# A bitmap pixel is one C64 hires pixel. The colour sprite is expanded 4x2,
# so outline the resulting 48x42 silhouette with one-pixel black pixels.
solid = set()
for y, row in enumerate(blocks[0]):
    row = row.ljust(12, ".")
    for x, char in enumerate(row):
        if char != ".":
            solid.update((xx, yy) for yy in range(y * 2, y * 2 + 2)
                         for xx in range(x * 4, x * 4 + 4))
outline = set()
for x, y in solid:
    for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):
        p = (x + dx, y + dy)
        if p not in solid and 0 <= p[0] < 48 and 0 <= p[1] < 42:
            outline.add(p)
points = sorted(outline, key=lambda p: (p[1], p[0]))
if len(points) > 255:
    raise SystemExit("Outline exceeds the assembly loop's 255 point limit")
out += ["OutlineCount = " + str(len(points)), "OutlineData:"]
flat = [v for point in points for v in point]
for i in range(0, len(flat), 16):
    out.append(asm_bytes(flat[i:i+16]))
(ROOT / "src/generated_sprites.asm").write_text("\n".join(out) + "\n")
