#!/usr/bin/env python3
"""Generate a hires dystopian neighborhood with colored cells and black ink."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
bitmap = bytearray(8192)
colors = bytearray(1024)


def pixel(x, y):
    """Set a black hires pixel. Zero bits reveal the cell's background color."""
    if 0 <= x < 320 and 0 <= y < 200:
        # Hires bitmap cells are 8 bytes wide in memory: the eight scanlines
        # for one character cell are adjacent, not the pixels across a row.
        address = (y & 7) + (y >> 3) * 320 + (x >> 3) * 8
        bitmap[address] |= 0x80 >> (x & 7)


def line(x0, y0, x1, y1):
    dx, dy = abs(x1 - x0), abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    err = dx - dy
    while True:
        pixel(x0, y0)
        if x0 == x1 and y0 == y1:
            break
        twice = 2 * err
        if twice > -dy:
            err -= dy
            x0 += sx
        if twice < dx:
            err += dx
            y0 += sy


def outline(x, y, width, height):
    line(x, y, x + width - 1, y)
    line(x, y + height - 1, x + width - 1, y + height - 1)
    line(x, y, x, y + height - 1)
    line(x + width - 1, y, x + width - 1, y + height - 1)


# Low-resolution cell colors create a bruised evening sky, concrete towers,
# and a dim street. The high screen-color nibble remains zero: bitmap 1-bits
# are black, while 0-bits reveal this single color for each 8x8 cell.
buildings = [
    (0, 70, 54, 111, 11),
    (48, 58, 51, 123, 12),
    (96, 78, 46, 103, 8),
    (139, 48, 64, 133, 11),
    (198, 67, 48, 114, 12),
    (242, 54, 43, 127, 8),
    (279, 75, 41, 106, 11),
]
for cy in range(25):
    for cx in range(40):
        x, y = cx * 8 + 4, cy * 8 + 4
        color = 6 if cy < 5 else (14 if cy < 9 else 6)
        if cy >= 9:
            color = 5 if cy < 18 else (8 if cy < 21 else (11 if cy % 2 else 12))
        for bx, by, bw, bh, facade in buildings:
            if bx <= x < bx + bw and by <= y < by + bh:
                color = facade
                # Muted cell-by-cell banding suggests stained concrete.
                if ((cx * 3 + cy * 5) % 11) == 0:
                    color = 12 if facade == 11 else (11 if facade == 12 else 9)
                break
        colors[cy * 40 + cx] = color

# The skyline is assembled from black structural lines: roof edges, corners,
# floors, broken windows, pipes, antennas, and hanging cables.
for i, (x, y, w, h, _) in enumerate(buildings):
    outline(x, y, w, h)
    # Uneven roof parapets and rooftop machinery.
    line(x + 4, y, x + 4, y - 5 - (i % 3) * 2)
    line(x + 4, y - 5 - (i % 3) * 2, x + 12, y - 5 - (i % 3) * 2)
    line(x + 12, y - 5 - (i % 3) * 2, x + 12, y)
    line(x + w - 13, y, x + w - 13, y - 8)
    line(x + w - 16, y - 8, x + w - 10, y - 8)
    # Floor slabs and deliberately interrupted facade seams.
    floor = y + 17
    while floor < y + h - 4:
        line(x + 2, floor, x + w // 2 - 4, floor)
        line(x + w // 2 + 3, floor, x + w - 2, floor)
        floor += 19
    # Recessed windows. The colored cell beneath remains visible as glass.
    for wy in range(y + 8, y + h - 9, 15):
        for wx in range(x + 7, x + w - 8, 13):
            width = 5 if (wx + wy) % 3 else 6
            height = 7 if (wx + wy) % 2 else 8
            outline(wx, wy, width, height)
            if (wx + wy + i) % 4 == 0:
                line(wx + 2, wy + 2, wx + width - 2, wy + height - 3)
            elif (wx * 3 + wy) % 5 == 0:
                line(wx + 1, wy + height - 2, wx + width - 2, wy + 2)
    # Drain pipes and a few cracked, exposed wall edges.
    pipe_x = x + w - 6
    line(pipe_x, y + 2, pipe_x, y + h - 3)
    line(pipe_x - 2, y + 20, pipe_x + 1, y + 20)
    line(x + 5, y + h // 2, x + 9, y + h // 2 + 6)
    line(x + 9, y + h // 2 + 6, x + 7, y + h // 2 + 13)

# Sagging utility wires, cables, and distant aerials break up the polluted sky.
line(0, 49, 83, 61)
line(83, 61, 160, 47)
line(160, 47, 238, 58)
line(238, 58, 319, 46)
for x, y in ((35, 54), (104, 57), (218, 55), (292, 50)):
    line(x, y - 7, x, y + 3)
    pixel(x - 2, y - 7)
    pixel(x + 2, y - 7)

# Street silhouette: broken kerb, drain slots, debris, and a simple barricade.
line(0, 166, 91, 166)
line(108, 166, 210, 166)
line(230, 166, 319, 166)
line(0, 174, 70, 174)
line(250, 174, 319, 174)
for x in (24, 37, 188, 202, 277, 291):
    line(x, 181, x + 5, 181)
    line(x + 1, 184, x + 4, 184)
outline(118, 155, 42, 15)
line(121, 158, 137, 171)
line(139, 158, 155, 171)
line(123, 170, 151, 170)
line(86, 190, 108, 188)
line(210, 192, 238, 190)

def asm_bytes(values):
    return "    !byte " + ",".join(f"${b:02x}" for b in values)


out = ["; Generated by tools/convert_background.py; do not edit.",
       "BackgroundBitmap:"]
for i in range(0, len(bitmap), 16):
    out.append(asm_bytes(bitmap[i:i + 16]))
out += ["BackgroundColors:"]
for i in range(0, len(colors), 16):
    out.append(asm_bytes(colors[i:i + 16]))
# Multicolor character pixels provide a transparent background code and a
# foreground code for black contour ink. The outline tracks sprites in 4-pixel
# vertical steps, leaving room for the background and contour glyphs together.
cells = []
for cy in range(25):
    for cx in range(40):
        rows = []
        for y in range(cy * 8, cy * 8 + 8):
            address = (y & 7) + (y >> 3) * 320 + cx * 8
            source = bitmap[address]
            encoded = 0
            for pair in range(4):
                bits = (source >> (6 - pair * 2)) & 0x03
                # Use shared code 10 for black linework; code 00 uses the
                # raster-colored sky/city fill.
                encoded = (encoded << 2) | (2 if bits else 0)
            rows.append(encoded)
        cells.append(tuple(rows))
from collections import Counter
blank = (0,) * 8
background_glyph_count = 32
frequent = [blank] + [g for g, _ in Counter(cells).most_common() if g != blank][:background_glyph_count - 1]
glyph_ids = {glyph: i for i, glyph in enumerate(frequent)}
codes = []
for glyph in cells:
    if glyph in glyph_ids:
        codes.append(glyph_ids[glyph])
        continue
    best_id, best_distance = 0, 65
    for candidate_id, candidate in enumerate(frequent):
        distance = sum((a ^ b).bit_count() for a, b in zip(glyph, candidate))
        if distance < best_distance:
            best_id, best_distance = candidate_id, distance
    codes.append(best_id)
character_out = ["; Generated character-mode background and moving contour glyphs; do not edit.", "CharacterGlyphs:"]

# Build the outer silhouette and internal feature contours as software glyphs.
blocks = []
current = []
for line_text in (ROOT / "data/characters.txt").read_text().splitlines():
    line_text = line_text.strip()
    if not line_text or line_text.startswith("#"):
        if current:
            blocks.append(current)
            current = []
    else:
        current.append(line_text)
if current:
    blocks.append(current)

outline_fragments = {}
outline_maps = []
character_sprite_data = []
for design, block in enumerate(blocks):
    solid = set()
    details = set()
    for y, row in enumerate(block):
        for x, ch in enumerate(row.ljust(12, ".")):
            if ch != ".":
                # Each multicolor sample is 2 pixels wide by 1 raster line;
                # sprite expansion makes it 4x2, spanning 48x42 overall.
                expanded = {(x * 4 + dx, y * 2 + dy)
                            for dx in range(4) for dy in range(2)}
                solid.update(expanded)
                if ch == "1":
                    details.update(expanded)
    contour = set()
    for x, y in solid:
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            p = (x + dx, y + dy)
            if p not in solid and -1 <= p[0] <= 48 and -1 <= p[1] <= 42:
                contour.add(p)
    # Add a one-pixel black seam around the light-grey feature regions, but
    # keep it inside the opaque sprite silhouette so it reads as interior ink.
    for x, y in details:
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            p = (x + dx, y + dy)
            if p in solid and p not in details:
                contour.add(p)
    # Preserve the original three sprite pixel codes. Black contours live in
    # the character layer outside the sprite, rather than consuming a sprite color.
    for y, row in enumerate(block):
        chars = list(row.ljust(12, "."))
        for offset in range(0, 12, 4):
            value = 0
            for ch in chars[offset:offset + 4]:
                value = (value << 2) | (0 if ch == "." else int(ch))
            character_sprite_data.append(value)
    character_sprite_data.append(0)  # one unused byte after each 21-row sprite
    for x_phase in (0, 4):
        for y_phase in range(8):
            tiles = {}
            for x, y in contour:
                # Leave one full character cell of padding so top/left contour
                # pixels have screen cells even when the sprite is cell-aligned.
                px, py = x + x_phase + 8, y + y_phase + 8
                tx, ty = px // 8, py // 8
                rows = tiles.setdefault((tx, ty), [0] * 8)
                # Multicolor characters stretch each 2-bit pixel to two
                # screen pixels. Code 10 uses the shared black VIC-II color.
                rows[py & 7] |= 0x02 << (6 - ((px & 7) // 2) * 2)
            tile_codes = [0] * 64
            for (tx, ty), rows in tiles.items():
                glyph = tuple(rows)
                if glyph not in outline_fragments:
                    # Zero means an empty contour cell in the 8x8 map.
                    outline_fragments[glyph] = len(outline_fragments) + 1
                tile_codes[ty * 8 + tx] = outline_fragments[glyph]
            outline_maps.append((design, x_phase, y_phase, tile_codes))

if len(character_sprite_data) != 4 * 64:
    raise SystemExit(f"Character sprite data must be 256 bytes, got {len(character_sprite_data)}")

all_glyphs = list(frequent) + [None] * (256 - len(frequent))
for i, glyph in enumerate(all_glyphs):
    character_out.append(asm_bytes(glyph or blank))
character_out += ["CharacterScreen:"]
for i in range(0, len(codes), 16):
    character_out.append(asm_bytes(codes[i:i + 16]))
character_out += ["CharacterColors:"]
for i in range(0, len(colors), 16):
    character_out.append(asm_bytes([(c & 7) | 8 for c in colors[i:i + 16]]))
map_labels = [f"CharacterOutline_{d}_{xp}_{yp}" for d, xp, yp, _ in outline_maps]
character_out += ["CharacterOutlineLo:", "    !byte " + ",".join(f"<{n}" for n in map_labels),
                  "CharacterOutlineHi:", "    !byte " + ",".join(f">{n}" for n in map_labels)]
character_out += ["CharacterSpriteData:"]
for i in range(0, len(character_sprite_data), 16):
    character_out.append(asm_bytes(character_sprite_data[i:i + 16]))
# 16-bit map entries address all 425 distinct contour tiles generated by the
# four 2x sprites. Keep the 8 KiB map block and the contour glyph atlas outside
# the VIC-visible bank; the CPU reads them while composing the hidden charset.
character_out += ["    * = $a000"]
for label, (_, _, _, tile_codes) in zip(map_labels, outline_maps):
    character_out.append(label + ":")
    tile_map = [byte for code in tile_codes for byte in (code & 0xff, code >> 8)]
    for i in range(0, len(tile_map), 16):
        character_out.append(asm_bytes(tile_map[i:i + 16]))
character_out += ["    * = $c100", "CharacterContourGlyphs:"]
character_out.append(asm_bytes(blank))  # contour map code zero means empty
for glyph in outline_fragments:
    character_out.append(asm_bytes(glyph))
(ROOT / "src/generated_background.asm").write_text("\n".join(out) + "\n")
(ROOT / "src/generated_characters.asm").write_text("\n".join(character_out) + "\n")
