#!/usr/bin/env python3
"""Convert 12x21 text sprites into VIC-II multicolour data and bitmap outlines."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
blocks, current = [], []
for line in (ROOT / "data/characters.txt").read_text().splitlines():
    line = line.strip()
    if not line or line.startswith("#"):
        if current:
            blocks.append(current)
            current = []
        continue
    current.append(line)
if current:
    blocks.append(current)
if len(blocks) != 4 or any(len(b) != 21 for b in blocks):
    raise SystemExit("Expected four character designs, each exactly 21 rows")
for b in blocks:
    if any(len(row) > 12 or set(row) - set(".123") for row in b):
        raise SystemExit("Rows must be at most 12 pixels wide using .123")

def asm_bytes(values):
    return "    !byte " + ",".join(f"${x:02x}" for x in values)

out = ["; Generated by tools/convert_sprites.py; do not edit.", "SpriteData:"]
for n, block in enumerate(blocks):
    out.append(f"Sprite{n}:")
    for row in block:
        row = row.ljust(12, ".")
        bits = []
        for i in range(0, 12, 4):
            value = 0
            for char in row[i:i+4]:
                value = (value << 2) | (0 if char == "." else int(char))
            bits.append(value)
        out.append(asm_bytes(bits))
    out.append("    !byte 0")
    out.append("")

# Precombine the outer contour and feature contours into 42 scanlines of six
# bytes. The assembly shifts each scanline to the actor's pixel X alignment,
# then ORs whole bytes into the hires bitmap instead of plotting each pixel.
for n, block in enumerate(blocks):
    solid = set()
    detail_solid = set()
    for y, row in enumerate(block):
        row = row.ljust(12, ".")
        for x, char in enumerate(row):
            expanded = {(xx, yy) for yy in range(y * 2, y * 2 + 2)
                        for xx in range(x * 4, x * 4 + 4)}
            if char != ".":
                solid.update(expanded)
            if char == "1":
                detail_solid.update(expanded)
    contour = set()
    for shape in (solid, detail_solid):
        for x, y in shape:
            for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):
                p = (x + dx, y + dy)
                if p not in shape and 0 <= p[0] < 48 and 0 <= p[1] < 42:
                    contour.add(p)
    rows = bytearray(42 * 6)
    for x, y in contour:
        rows[y * 6 + x // 8] |= 0x80 >> (x & 7)
    out.append(f"ContourData{n}:")
    for i in range(0, len(rows), 16):
        out.append(asm_bytes(rows[i:i+16]))
out += ["ContourDataLo:", "    !byte " + ",".join(f"<ContourData{n}" for n in range(4)),
        "ContourDataHi:", "    !byte " + ",".join(f">ContourData{n}" for n in range(4))]
(ROOT / "src/generated_sprites.asm").write_text("\n".join(out) + "\n")
