#!/usr/bin/env python3
"""Generate a hires C64 sky-and-hills background plus per-cell colors."""
from math import sin
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
bitmap = bytearray(8192)

# The bitmap foreground is reserved for actor contours and internal detail.
# The low nibble supplies the colored sky and hills behind transparent sprites.
colors = bytearray(1024)
for cy in range(25):
    y = cy * 8 + 4
    for cx in range(40):
        far_hill = 119 + int(9 * sin(cx * 0.31))
        near_hill = 143 + int(11 * sin(cx * 0.21 + 1.0))
        if y < far_hill:
            bg = 6 if cy < 9 else 4
        elif y < near_hill:
            bg = 11 if (cx + cy) % 5 else 12
        elif y < 168:
            bg = 5 if (cx // 5 + cy) % 4 else 13
        else:
            bg = 5 if cy % 2 else 13
        # A winding dark river through the valley.
        river_x = 24 + (cy - 18) * 2
        if cy >= 17 and abs(cx - river_x) <= 1:
            bg = 6
        colors[cy * 40 + cx] = bg

def asm_bytes(values):
    return "    !byte " + ",".join(f"${b:02x}" for b in values)

out = ["; Generated by tools/convert_background.py; do not edit.",
       "BackgroundBitmap:"]
for i in range(0, len(bitmap), 16):
    out.append(asm_bytes(bitmap[i:i+16]))
out += ["BackgroundColors:"]
for i in range(0, len(colors), 16):
    out.append(asm_bytes(colors[i:i+16]))
(ROOT / "src/generated_background.asm").write_text("\n".join(out) + "\n")
