#!/usr/bin/env python3
"""Convert 12x21 text sprites into VIC-II multicolour data and bitmap outlines."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
blocks, current = [], []
for line in (ROOT / "data/characters.txt").read_text().splitlines():
    line = line.strip()
    if not line or line.startswith("#"):
        if current:
            blocks.append(current)
            current = []
        continue
    current.append(line)
if current:
    blocks.append(current)
if len(blocks) != 4 or any(len(b) != 21 for b in blocks):
    raise SystemExit("Expected four character designs, each exactly 21 rows")
for b in blocks:
    if any(len(row) > 12 or set(row) - set(".123") for row in b):
        raise SystemExit("Rows must be at most 12 pixels wide using .123")

def asm_bytes(values):
    return "    !byte " + ",".join(f"${x:02x}" for x in values)

out = ["; Generated by tools/convert_sprites.py; do not edit.", "SpriteData:"]
for n, block in enumerate(blocks):
    out.append(f"Sprite{n}:")
    for row in block:
        row = row.ljust(12, ".")
        bits = []
        for i in range(0, 12, 4):
            value = 0
            for char in row[i:i+4]:
                value = (value << 2) | (0 if char == "." else int(char))
            bits.append(value)
        out.append(asm_bytes(bits))
    out.append("    !byte 0")
    out.append("")

# Precompute horizontally shifted masks for the two reachable alignments (0
# and 4 pixels). Each
# nonempty row stores its row number and only the occupied byte-position/value
# pairs, so the renderer never tests empty byte slots.
out.append("* = $8000")  # Keep tables outside the bitmap buffers at $6000/$a000.
mask_tables = {"Silhouette": [], "Contour": []}
for n, block in enumerate(blocks):
    solid = set()
    detail_solid = set()
    for y, row in enumerate(block):
        row = row.ljust(12, ".")
        for x, char in enumerate(row):
            expanded = {(xx, yy) for yy in range(y * 2, y * 2 + 2)
                        for xx in range(x * 4, x * 4 + 4)}
            if char != ".":
                solid.update(expanded)
            if char == "1":
                detail_solid.update(expanded)
    contour = set()
    for shape in (solid, detail_solid):
        for x, y in shape:
            for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):
                p = (x + dx, y + dy)
                if p not in shape and 0 <= p[0] < 48 and 0 <= p[1] < 42:
                    contour.add(p)
    for label, points in (("Silhouette", solid), ("Contour", contour)):
        for shift in (0, 4):
            rows = [bytearray(7) for _ in range(42)]
            for x, y in points:
                px = x + shift
                rows[y][px // 8] |= 0x80 >> (px & 7)
            row_records = []
            for y, row in enumerate(rows):
                entries = [(byte_index, value)
                           for byte_index, value in enumerate(row) if value]
                if entries:
                    row_records.append((y, entries))
            name = f"{label}Sparse{n}_{shift}"
            out.append(f"{name}:")
            for y, entries in row_records:
                encoded = [y, len(entries)]
                for byte_index, value in entries:
                    encoded.extend((byte_index, value))
                out.append(asm_bytes(encoded))
            mask_tables[label].append((name, len(row_records)))

for label, entries in mask_tables.items():
    out += [f"{label}SparseLo:", "    !byte " + ",".join(f"<{name}" for name, _ in entries),
            f"{label}SparseHi:", "    !byte " + ",".join(f">{name}" for name, _ in entries),
            f"{label}SparseRows:", "    !byte " + ",".join(f"${count:02x}" for _, count in entries)]
(ROOT / "src/generated_sprites.asm").write_text("\n".join(out) + "\n")
